import { knowledgePages } from "@ironworksai/db";
import { type KnowledgeFrontmatter, renderFrontmatter } from "@ironworksai/shared";

/**
 * Drizzle-inferred row type for the `knowledge_pages` table - kept narrow so
 * this module stays decoupled from server-side enrichment objects.
 */
export type KnowledgePage = typeof knowledgePages.$inferSelect;

/**
 * Slugs whose first segment is one of these stays at the zip root with that
 * prefix preserved. Everything else lives under `knowledge/`. The set mirrors
 * the canonical entity-folder layout used elsewhere in the vault export
 * (decisions/, agents/, finance/, skills/, issues/).
 */
const TOP_LEVEL_PREFIXES = new Set(["decisions", "agents", "finance", "skills", "issues"]);

/**
 * Characters that are unsafe across Windows / macOS / Linux filesystems OR
 * have meaning in zip path resolution. Replaced with `_` per-segment so the
 * archive extracts cleanly on every host. We keep `/` valid (it's the
 * segment separator) and only sanitize within a segment.
 */
// biome-ignore lint/suspicious/noControlCharactersInRegex: intentional - strip ASCII control chars from filesystem paths
const UNSAFE_CHARS_RE = /[<>:"\\|?*\x00-\x1f]/g;

function sanitizeSegment(segment: string): string {
  return segment.replace(UNSAFE_CHARS_RE, "_");
}

/**
 * Map a knowledge page slug to its zip-relative path.
 *
 * Top-level prefixes (decisions/, agents/, finance/, skills/, issues/) keep
 * their prefix at the archive root. All other slugs go under `knowledge/`.
 * Each segment is sanitized so unsafe characters become `_`.
 */
export function pathFromSlug(slug: string): string {
  const segments = slug.split("/").map(sanitizeSegment);
  const [first] = segments;
  const useTopLevel = first !== undefined && TOP_LEVEL_PREFIXES.has(first);
  const prefixed = useTopLevel ? segments : ["knowledge", ...segments];
  return `${prefixed.join("/")}.md`;
}

export interface RenderedFile {
  path: string;
  content: string;
}

/**
 * Render a knowledge_pages row to a vault file: canonical YAML frontmatter
 * + verbatim markdown body. Optional fields (aliases, document_type, etc.)
 * are omitted from the YAML when null/empty so round-trip parsing matches.
 */
export function renderKnowledgePage(page: KnowledgePage): RenderedFile {
  const fm: KnowledgeFrontmatter = {
    id: page.id,
    type: "knowledge",
    title: page.title,
    slug: page.slug,
    created_at: page.createdAt.toISOString(),
    updated_at: page.updatedAt.toISOString(),
    auto_generated: page.autoGenerated,
    revision_number: page.revisionNumber,
  };

  // Only attach aliases when the row actually has any - empty array is the
  // default and would emit `aliases: []` which the parser then has to ignore.
  if (page.aliases && page.aliases.length > 0) {
    fm.aliases = page.aliases;
  }
  if (page.documentType) fm.document_type = page.documentType;
  if (page.department) fm.department = page.department;
  if (page.deliverableStatus) fm.deliverable_status = page.deliverableStatus;
  if (page.agentId) fm.agent_id = page.agentId;
  if (page.projectId) fm.project_id = page.projectId;

  const frontmatter = renderFrontmatter(fm);
  const body = page.body ?? "";
  // Blank line between frontmatter delimiter and body is the keepachangelog/
  // hugo/jekyll convention; markdown parsers tolerate either, but the blank
  // line keeps the file readable when opened raw.
  const content = `${frontmatter}\n${body}${body.endsWith("\n") ? "" : "\n"}`;

  return {
    path: pathFromSlug(page.slug),
    content,
  };
}
