import type { RenderedFile } from "./render-knowledge.js";

/**
 * Counts of vault entities surfaced in the index page's "Stats" section.
 * Computed by the composer during its walk so the index always reflects
 * exactly what was emitted into this archive (not a stale snapshot).
 */
export interface IndexCounts {
  knowledgePages: number;
  decisions: number;
  agents: number;
  issues: number;
  skills: number;
}

export interface IndexInput {
  companyName: string;
  generatedAt: Date;
  counts: IndexCounts;
}

/**
 * Render the vault root `index.md` - table of contents + per-section counts.
 * Body shape is fixed by the P3 spec; we hand-emit YAML rather than going
 * through `renderFrontmatter` because "index" isn't a canonical EntityType
 * (the discriminated union doesn't include it) and this file has no
 * meaningful round-trip back into the DB.
 */
export function renderIndex(input: IndexInput): RenderedFile {
  const { companyName, generatedAt, counts } = input;
  const generatedIso = generatedAt.toISOString();
  const generatedDate = generatedIso.slice(0, 10);

  // YAML escaping: company name might contain a colon ("Acme: Co"), which
  // would break a bare `title: <name>` line. Wrapping in double-quotes and
  // escaping interior backslashes + quotes keeps the YAML valid for every
  // legal company name without pulling in js-yaml just for one string.
  const yamlTitle = quoteYaml(`${companyName} Vault`);

  const frontmatter = ["---", "type: index", `title: ${yamlTitle}`, `generated_at: ${generatedIso}`, "---", ""].join(
    "\n",
  );

  const body = [
    `# ${companyName} Knowledge Vault`,
    "",
    `This vault was exported from Ironworks on ${generatedDate}.`,
    "",
    "## Sections",
    "- [[knowledge/]] - Authored knowledge pages",
    "- [[decisions/]] - Logged decisions with backlinks to source",
    "- [[agents/]] - Agent profiles + run histories",
    "- [[issues/]] - Issue records with comments",
    "- [[finance/cost-rollups/]] - Weekly + monthly cost summaries",
    "- [[skills/]] - Skill libraries",
    "",
    "## Stats",
    `- Knowledge pages: ${counts.knowledgePages}`,
    `- Decisions: ${counts.decisions}`,
    `- Agents: ${counts.agents}`,
    `- Issues: ${counts.issues}`,
    `- Skills: ${counts.skills}`,
    "- Generated by Ironworks vault-export",
    "",
  ].join("\n");

  return {
    path: "index.md",
    content: `${frontmatter}${body}`,
  };
}

/**
 * Minimal double-quoted YAML scalar emitter. Sufficient for the title field
 * (a single ASCII-ish line). Keeps the renderer free of a YAML dep for one
 * value.
 */
function quoteYaml(s: string): string {
  return `"${s.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}
