import { describe, expect, it } from "vitest";
import { type KnowledgePage, pathFromSlug, renderKnowledgePage } from "../render-knowledge.js";

/**
 * Build a minimal KnowledgePage with sane defaults - individual tests
 * override only the fields they care about. Avoids `as any` while still
 * staying terse.
 */
function makePage(overrides: Partial<KnowledgePage> = {}): KnowledgePage {
  const base: KnowledgePage = {
    id: "00000000-0000-0000-0000-000000000001",
    companyId: "00000000-0000-0000-0000-0000000000aa",
    slug: "engineering/api-conventions",
    title: "API Conventions",
    body: "Body content here.",
    visibility: "company",
    projectId: null,
    revisionNumber: 1,
    isSeeded: null,
    createdByAgentId: null,
    createdByUserId: null,
    updatedByAgentId: null,
    updatedByUserId: null,
    agentId: null,
    documentType: null,
    autoGenerated: false,
    department: null,
    deliverableStatus: null,
    aliases: [],
    createdAt: new Date("2026-05-01T00:00:00.000Z"),
    updatedAt: new Date("2026-05-02T12:34:56.000Z"),
  };
  return { ...base, ...overrides };
}

describe("pathFromSlug", () => {
  const cases: Array<[string, string]> = [
    ["engineering/api-conventions", "knowledge/engineering/api-conventions.md"],
    ["decisions/d-12345", "decisions/d-12345.md"],
    ["agents/foo/runs/2026-05-01/abc12345", "agents/foo/runs/2026-05-01/abc12345.md"],
    ["finance/cost-rollups/weekly/2026-W18", "finance/cost-rollups/weekly/2026-W18.md"],
    ["skills/code-review", "skills/code-review.md"],
    ["issues/abc-123", "issues/abc-123.md"],
    ["top-level-only", "knowledge/top-level-only.md"],
    ["foo/bar:baz", "knowledge/foo/bar_baz.md"],
  ];

  for (const [input, expected] of cases) {
    it(`maps ${input} → ${expected}`, () => {
      expect(pathFromSlug(input)).toBe(expected);
    });
  }
});

describe("renderKnowledgePage", () => {
  it("renders all fields when populated", () => {
    const page = makePage({
      slug: "engineering/api-conventions",
      title: "API Conventions",
      body: "# Hello\n\nWorld.",
      aliases: ["api-conv", "conventions-api"],
      documentType: "report",
      department: "engineering",
      deliverableStatus: "approved",
      autoGenerated: true,
      revisionNumber: 4,
      agentId: "00000000-0000-0000-0000-0000000000ab",
      projectId: "00000000-0000-0000-0000-0000000000ac",
    });

    const result = renderKnowledgePage(page);

    expect(result.path).toBe("knowledge/engineering/api-conventions.md");
    expect(result.content).toContain("type: knowledge");
    expect(result.content).toContain("slug: engineering/api-conventions");
    expect(result.content).toContain("title: API Conventions");
    expect(result.content).toContain("aliases:");
    expect(result.content).toContain("- api-conv");
    expect(result.content).toContain("document_type: report");
    expect(result.content).toContain("department: engineering");
    expect(result.content).toContain("deliverable_status: approved");
    expect(result.content).toContain("auto_generated: true");
    expect(result.content).toContain("revision_number: 4");
    expect(result.content).toContain("agent_id: 00000000-0000-0000-0000-0000000000ab");
    expect(result.content).toContain("project_id: 00000000-0000-0000-0000-0000000000ac");
    expect(result.content).toContain("# Hello\n\nWorld.");
    // Frontmatter block delimited by --- on either side
    expect(result.content.startsWith("---\n")).toBe(true);
    expect(result.content).toMatch(/---\n\n# Hello/);
  });

  it("omits null/empty optional keys from frontmatter", () => {
    const page = makePage({
      aliases: [],
      documentType: null,
      department: null,
      deliverableStatus: null,
      agentId: null,
      projectId: null,
    });

    const result = renderKnowledgePage(page);

    expect(result.content).not.toContain("aliases");
    expect(result.content).not.toContain("document_type");
    expect(result.content).not.toContain("department");
    expect(result.content).not.toContain("deliverable_status");
    expect(result.content).not.toContain("agent_id");
    expect(result.content).not.toContain("project_id");
  });

  it("passes wikilink syntax through the body untouched", () => {
    const page = makePage({
      body: "See [[other-page]] and [[some/nested-slug]] for details.",
    });

    const result = renderKnowledgePage(page);

    expect(result.content).toContain("[[other-page]]");
    expect(result.content).toContain("[[some/nested-slug]]");
  });

  it("renders empty body as frontmatter + blank section", () => {
    const page = makePage({ body: "" });

    const result = renderKnowledgePage(page);

    // Frontmatter ends with `---\n` and we expect a blank line then nothing
    expect(result.content.endsWith("---\n\n\n")).toBe(true);
  });
});
