import { randomUUID } from "node:crypto";
import express from "express";
import request from "supertest";
import { beforeEach, describe, expect, it, vi } from "vitest";

// ── Mock data ───────────────────────────────────────────────────────────────

const COMPANY_ID = randomUUID();
const USER_ID = randomUUID();
const DELIVERABLE_ID = randomUUID();

const MOCK_DELIVERABLE = {
  id: DELIVERABLE_ID,
  companyId: COMPANY_ID,
  slug: "test-report",
  title: "Test Report",
  documentType: "weekly-report",
  deliverableStatus: "draft",
  agentId: null,
  createdByAgentId: null,
  autoGenerated: false,
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
  agentName: null,
  agentRole: null,
};

// ── DB mock ─────────────────────────────────────────────────────────────────

const mockSelectRows = vi.hoisted(() => vi.fn());
const mockUpdateRows = vi.hoisted(() => vi.fn());

function createFakeDb() {
  const returning = vi.fn().mockImplementation(() => mockUpdateRows());
  const whereUpdate = vi.fn().mockReturnValue({ returning });
  const set = vi.fn().mockReturnValue({ where: whereUpdate });
  const updateFrom = vi.fn().mockReturnValue({ set });

  const limit = vi.fn().mockImplementation(() => mockSelectRows());
  const whereSelectChained = vi.fn().mockReturnValue({ limit });
  const orderBy = vi.fn().mockImplementation(() => mockSelectRows());
  const whereSelect = vi.fn().mockReturnValue({ orderBy, limit });
  const leftJoin = vi.fn().mockReturnValue({ where: whereSelect });
  const from = vi.fn().mockReturnValue({ where: whereSelectChained, leftJoin });
  const selectObj = vi.fn().mockReturnValue({ from });

  return {
    select: selectObj,
    update: vi.fn().mockReturnValue({ set }),
  } as any;
}

// ── Service mocks ───────────────────────────────────────────────────────────

const mockLogActivity = vi.hoisted(() => vi.fn());

vi.mock("../services/activity-log.js", () => ({
  logActivity: mockLogActivity,
  setPluginEventBus: vi.fn(),
}));

vi.mock("../middleware/logger.js", () => ({
  logger: { error: vi.fn(), info: vi.fn(), warn: vi.fn(), debug: vi.fn() },
}));

// Mock assertCanWrite to avoid DB calls for membership checks
vi.mock("../routes/authz.js", async (importOriginal) => {
  const original = (await importOriginal()) as any;
  return {
    ...original,
    assertCanWrite: vi.fn().mockResolvedValue(undefined),
  };
});

// ── App builder ─────────────────────────────────────────────────────────────

async function createApp(actor: Record<string, unknown>, fakeDb?: any) {
  const { deliverableRoutes } = await import("../routes/deliverables.js");
  const { errorHandler } = await import("../middleware/error-handler.js");

  const app = express();
  app.use(express.json());
  app.use((req, _res, next) => {
    (req as any).actor = actor;
    next();
  });
  app.use("/api", deliverableRoutes(fakeDb ?? createFakeDb()));
  app.use(errorHandler);
  return app;
}

function boardUser(userId: string, companyIds: string[]) {
  return { type: "board", userId, companyIds, isInstanceAdmin: false, source: "session" };
}

function noActor() {
  return { type: "none" };
}

// ── Tests ───────────────────────────────────────────────────────────────────

describe("deliverable routes", () => {
  beforeEach(() => {
    vi.clearAllMocks();
    mockSelectRows.mockResolvedValue([MOCK_DELIVERABLE]);
    mockUpdateRows.mockResolvedValue([{ ...MOCK_DELIVERABLE, deliverableStatus: "approved" }]);
    mockLogActivity.mockResolvedValue(undefined);
  });

  describe("GET /api/companies/:companyId/deliverables", () => {
    it("returns deliverables for authorized user", async () => {
      const app = await createApp(boardUser(USER_ID, [COMPANY_ID]));
      const res = await request(app).get(`/api/companies/${COMPANY_ID}/deliverables`);

      expect(res.status).toBe(200);
      expect(res.body).toHaveLength(1);
      expect(res.body[0]).toMatchObject({ title: "Test Report", deliverableStatus: "draft" });
    });

    it("rejects unauthenticated requests with 401", async () => {
      const app = await createApp(noActor());
      const res = await request(app).get(`/api/companies/${COMPANY_ID}/deliverables`);
      expect(res.status).toBe(401);
    });

    it("rejects cross-company access with 403", async () => {
      const otherCompany = randomUUID();
      const app = await createApp(boardUser(USER_ID, [COMPANY_ID]));
      const res = await request(app).get(`/api/companies/${otherCompany}/deliverables`);
      expect(res.status).toBe(403);
    });

    it("passes status filter for valid status", async () => {
      const app = await createApp(boardUser(USER_ID, [COMPANY_ID]));
      const res = await request(app).get(`/api/companies/${COMPANY_ID}/deliverables?status=approved`);
      expect(res.status).toBe(200);
    });

    it("ignores invalid status filter gracefully", async () => {
      const app = await createApp(boardUser(USER_ID, [COMPANY_ID]));
      const res = await request(app).get(`/api/companies/${COMPANY_ID}/deliverables?status=bogus`);
      expect(res.status).toBe(200);
    });
  });

  describe("PATCH /api/companies/:companyId/deliverables/:id", () => {
    it("updates deliverable status for authorized user", async () => {
      mockSelectRows.mockResolvedValue([
        {
          id: DELIVERABLE_ID,
          companyId: COMPANY_ID,
          deliverableStatus: "draft",
          documentType: "weekly-report",
          title: "Test Report",
        },
      ]);
      const app = await createApp(boardUser(USER_ID, [COMPANY_ID]));
      const res = await request(app)
        .patch(`/api/companies/${COMPANY_ID}/deliverables/${DELIVERABLE_ID}`)
        .send({ deliverableStatus: "approved" });

      expect(res.status).toBe(200);
    });

    it("rejects unauthenticated patch with 401", async () => {
      const app = await createApp(noActor());
      const res = await request(app)
        .patch(`/api/companies/${COMPANY_ID}/deliverables/${DELIVERABLE_ID}`)
        .send({ deliverableStatus: "approved" });
      expect(res.status).toBe(401);
    });

    it("rejects invalid deliverableStatus with 400", async () => {
      const app = await createApp(boardUser(USER_ID, [COMPANY_ID]));
      const res = await request(app)
        .patch(`/api/companies/${COMPANY_ID}/deliverables/${DELIVERABLE_ID}`)
        .send({ deliverableStatus: "invalid_status" });

      expect(res.status).toBe(400);
      expect(res.body.error).toContain("deliverableStatus must be one of");
    });

    it("rejects missing deliverableStatus with 400", async () => {
      const app = await createApp(boardUser(USER_ID, [COMPANY_ID]));
      const res = await request(app).patch(`/api/companies/${COMPANY_ID}/deliverables/${DELIVERABLE_ID}`).send({});

      expect(res.status).toBe(400);
    });

    it("returns 404 for non-existent deliverable", async () => {
      mockSelectRows.mockResolvedValue([]);
      const app = await createApp(boardUser(USER_ID, [COMPANY_ID]));
      const res = await request(app)
        .patch(`/api/companies/${COMPANY_ID}/deliverables/${randomUUID()}`)
        .send({ deliverableStatus: "approved" });

      expect(res.status).toBe(404);
    });

    it("logs activity after status update", async () => {
      mockSelectRows.mockResolvedValue([
        {
          id: DELIVERABLE_ID,
          companyId: COMPANY_ID,
          deliverableStatus: "draft",
          documentType: "weekly-report",
          title: "Test Report",
        },
      ]);
      const app = await createApp(boardUser(USER_ID, [COMPANY_ID]));
      await request(app)
        .patch(`/api/companies/${COMPANY_ID}/deliverables/${DELIVERABLE_ID}`)
        .send({ deliverableStatus: "approved" });

      expect(mockLogActivity).toHaveBeenCalledWith(
        expect.anything(),
        expect.objectContaining({
          action: "deliverable.status_updated",
          entityType: "knowledge_page",
        }),
      );
    });
  });
});
