import { randomUUID } from "node:crypto";
import express from "express";
import request from "supertest";
import { beforeEach, describe, expect, it, vi } from "vitest";

const COMPANY_ID = randomUUID();
const OTHER_COMPANY_ID = randomUUID();
const USER_ID = randomUUID();
const PAGE_ID = randomUUID();
const FOREIGN_PAGE_ID = randomUUID();

const MOCK_PAGE = {
  id: PAGE_ID,
  companyId: COMPANY_ID,
  title: "Onboarding Guide",
  slug: "onboarding-guide",
  body: "# Welcome",
  visibility: "company",
  autoGenerated: false,
  documentType: null,
};

const FOREIGN_PAGE = { ...MOCK_PAGE, id: FOREIGN_PAGE_ID, companyId: OTHER_COMPANY_ID };

const mockKnowledgeService = vi.hoisted(() => ({
  getById: vi.fn(),
  list: vi.fn(),
  getBySlug: vi.fn(),
  create: vi.fn(),
  update: vi.fn(),
  remove: vi.fn(),
  listRevisions: vi.fn(),
  getRevision: vi.fn(),
  revertToRevision: vi.fn(),
  seedDefaults: vi.fn(),
}));

const mockGetBacklinks = vi.hoisted(() => vi.fn());
const mockGetNeighborhood = vi.hoisted(() => vi.fn());

vi.mock("../services/knowledge.js", () => ({
  knowledgeService: () => mockKnowledgeService,
}));

vi.mock("../services/knowledge-links/queries.js", () => ({
  getBacklinks: mockGetBacklinks,
  getNeighborhood: mockGetNeighborhood,
}));

vi.mock("../middleware/logger.js", () => ({
  logger: { error: vi.fn(), info: vi.fn(), warn: vi.fn(), debug: vi.fn() },
}));

async function createApp(actor: Record<string, unknown>) {
  const { knowledgeLinksRoutes } = await import("../routes/knowledge-links.js");
  const { errorHandler } = await import("../middleware/error-handler.js");

  const app = express();
  app.use(express.json());
  app.use((req, _res, next) => {
    // biome-ignore lint/suspicious/noExplicitAny: actor attached at runtime by middleware
    (req as any).actor = actor;
    next();
  });
  // biome-ignore lint/suspicious/noExplicitAny: stub Drizzle DB; queries are mocked
  const fakeDb = {} as any;
  app.use("/api", knowledgeLinksRoutes(fakeDb));
  app.use(errorHandler);
  return app;
}

function boardUser(userId: string, companyIds: string[]) {
  return { type: "board", userId, companyIds, isInstanceAdmin: false, source: "session" };
}

describe("knowledge-links routes", () => {
  beforeEach(() => {
    vi.clearAllMocks();
    mockKnowledgeService.getById.mockImplementation(async (id: string) => {
      if (id === PAGE_ID) return MOCK_PAGE;
      if (id === FOREIGN_PAGE_ID) return FOREIGN_PAGE;
      return null;
    });
    mockGetBacklinks.mockResolvedValue([]);
    mockGetNeighborhood.mockResolvedValue({
      nodes: [
        { id: PAGE_ID, slug: "onboarding-guide", title: "Onboarding Guide", isCurrent: true, documentType: null },
      ],
      edges: [],
    });
  });

  describe("GET /api/knowledge-pages/:id/backlinks", () => {
    it("returns 200 with empty backlinks", async () => {
      const app = await createApp(boardUser(USER_ID, [COMPANY_ID]));
      const res = await request(app).get(`/api/knowledge-pages/${PAGE_ID}/backlinks`);
      expect(res.status).toBe(200);
      expect(res.body).toEqual({ backlinks: [] });
    });

    it("returns 200 with seeded backlinks", async () => {
      const rows = [
        { pageId: randomUUID(), slug: "a", title: "A", anchor: null, documentType: null, updatedAt: new Date() },
        { pageId: randomUUID(), slug: "b", title: "B", anchor: "intro", documentType: null, updatedAt: new Date() },
      ];
      mockGetBacklinks.mockResolvedValue(rows);
      const app = await createApp(boardUser(USER_ID, [COMPANY_ID]));
      const res = await request(app).get(`/api/knowledge-pages/${PAGE_ID}/backlinks`);
      expect(res.status).toBe(200);
      expect(res.body.backlinks).toHaveLength(2);
      expect(res.body.backlinks[1].anchor).toBe("intro");
    });

    it("returns 400 on invalid UUID", async () => {
      const app = await createApp(boardUser(USER_ID, [COMPANY_ID]));
      const res = await request(app).get(`/api/knowledge-pages/not-a-uuid/backlinks`);
      expect(res.status).toBe(400);
    });

    it("returns 404 on non-existent page", async () => {
      const app = await createApp(boardUser(USER_ID, [COMPANY_ID]));
      const res = await request(app).get(`/api/knowledge-pages/${randomUUID()}/backlinks`);
      expect(res.status).toBe(404);
    });

    it("returns 404 on cross-tenant page (no leak via 403)", async () => {
      const app = await createApp(boardUser(USER_ID, [COMPANY_ID]));
      const res = await request(app).get(`/api/knowledge-pages/${FOREIGN_PAGE_ID}/backlinks`);
      expect(res.status).toBe(404);
    });
  });

  describe("GET /api/knowledge-pages/:id/graph", () => {
    it("returns 200 with hops=2 default", async () => {
      const app = await createApp(boardUser(USER_ID, [COMPANY_ID]));
      const res = await request(app).get(`/api/knowledge-pages/${PAGE_ID}/graph`);
      expect(res.status).toBe(200);
      expect(res.body).toHaveProperty("nodes");
      expect(res.body).toHaveProperty("edges");
      expect(mockGetNeighborhood).toHaveBeenCalledWith(expect.anything(), {
        pageId: PAGE_ID,
        companyId: COMPANY_ID,
        hops: 2,
      });
    });

    it("returns 200 with hops=1 explicit", async () => {
      const app = await createApp(boardUser(USER_ID, [COMPANY_ID]));
      const res = await request(app).get(`/api/knowledge-pages/${PAGE_ID}/graph?hops=1`);
      expect(res.status).toBe(200);
      expect(mockGetNeighborhood).toHaveBeenCalledWith(expect.anything(), expect.objectContaining({ hops: 1 }));
    });

    it("returns 400 with hops=3", async () => {
      const app = await createApp(boardUser(USER_ID, [COMPANY_ID]));
      const res = await request(app).get(`/api/knowledge-pages/${PAGE_ID}/graph?hops=3`);
      expect(res.status).toBe(400);
    });

    it("returns 404 on non-existent page", async () => {
      const app = await createApp(boardUser(USER_ID, [COMPANY_ID]));
      const res = await request(app).get(`/api/knowledge-pages/${randomUUID()}/graph`);
      expect(res.status).toBe(404);
    });

    it("returns 404 on cross-tenant page (not 403)", async () => {
      const app = await createApp(boardUser(USER_ID, [COMPANY_ID]));
      const res = await request(app).get(`/api/knowledge-pages/${FOREIGN_PAGE_ID}/graph`);
      expect(res.status).toBe(404);
    });
  });
});
