import { randomUUID } from "node:crypto";
import express from "express";
import request from "supertest";
import { beforeEach, describe, expect, it, vi } from "vitest";

// ── Mock data ───────────────────────────────────────────────────────────────

const COMPANY_ID = randomUUID();
const USER_ID = randomUUID();
const PAGE_ID = randomUUID();

const MOCK_PAGE = {
  id: PAGE_ID,
  companyId: COMPANY_ID,
  title: "Onboarding Guide",
  slug: "onboarding-guide",
  body: "# Welcome\nThis is the onboarding guide.",
  visibility: "company",
  autoGenerated: false,
  documentType: null,
};

const MOCK_HR_PAGE = {
  ...MOCK_PAGE,
  id: randomUUID(),
  autoGenerated: true,
  documentType: "hiring-record",
};

const MOCK_REVISION = {
  id: randomUUID(),
  pageId: PAGE_ID,
  revisionNumber: 1,
  title: "Onboarding Guide",
  body: "# Welcome",
};

// ── Service mocks ───────────────────────────────────────────────────────────

const mockKnowledgeService = vi.hoisted(() => ({
  list: vi.fn(),
  getById: vi.fn(),
  getBySlug: vi.fn(),
  create: vi.fn(),
  update: vi.fn(),
  remove: vi.fn(),
  listRevisions: vi.fn(),
  getRevision: vi.fn(),
  revertToRevision: vi.fn(),
  seedDefaults: vi.fn(),
}));

const mockLogActivity = vi.hoisted(() => vi.fn());

vi.mock("../services/knowledge.js", () => ({
  knowledgeService: () => mockKnowledgeService,
}));

vi.mock("../services/activity-log.js", () => ({
  logActivity: mockLogActivity,
  setPluginEventBus: vi.fn(),
}));

vi.mock("../middleware/logger.js", () => ({
  logger: { error: vi.fn(), info: vi.fn(), warn: vi.fn(), debug: vi.fn() },
}));

// ── App builder ─────────────────────────────────────────────────────────────

async function createApp(actor: Record<string, unknown>) {
  const { knowledgeRoutes } = await import("../routes/knowledge.js");
  const { errorHandler } = await import("../middleware/error-handler.js");

  const app = express();
  app.use(express.json());
  app.use((req, _res, next) => {
    // biome-ignore lint/suspicious/noExplicitAny: actor prop is attached to Express Request by middleware but not declared in its TypeScript type
    (req as any).actor = actor;
    next();
  });
  // biome-ignore lint/suspicious/noExplicitAny: mock Drizzle DB or storage object for unit tests; real type requires full schema-aware Drizzle instance
  const fakeDb = {} as any;
  app.use("/api", knowledgeRoutes(fakeDb));
  app.use(errorHandler);
  return app;
}

function boardUser(userId: string, companyIds: string[]) {
  return { type: "board", userId, companyIds, isInstanceAdmin: false, source: "session" };
}

function noActor() {
  return { type: "none" };
}

// ── Tests ───────────────────────────────────────────────────────────────────

describe("knowledge routes", () => {
  beforeEach(() => {
    vi.clearAllMocks();
    mockKnowledgeService.list.mockResolvedValue([MOCK_PAGE]);
    mockKnowledgeService.getById.mockResolvedValue(MOCK_PAGE);
    mockKnowledgeService.getBySlug.mockResolvedValue(MOCK_PAGE);
    mockKnowledgeService.create.mockResolvedValue(MOCK_PAGE);
    mockKnowledgeService.update.mockResolvedValue(MOCK_PAGE);
    mockKnowledgeService.listRevisions.mockResolvedValue([MOCK_REVISION]);
    mockKnowledgeService.getRevision.mockResolvedValue(MOCK_REVISION);
    mockKnowledgeService.revertToRevision.mockResolvedValue(MOCK_PAGE);
    mockKnowledgeService.seedDefaults.mockResolvedValue({ created: 3 });
  });

  describe("GET /api/companies/:companyId/knowledge", () => {
    it("lists knowledge pages for authorized user", async () => {
      const app = await createApp(boardUser(USER_ID, [COMPANY_ID]));
      const res = await request(app).get(`/api/companies/${COMPANY_ID}/knowledge`);

      expect(res.status).toBe(200);
      expect(res.body).toHaveLength(1);
      expect(res.body[0]).toMatchObject({ title: "Onboarding Guide" });
    });

    it("rejects unauthenticated requests with 401", async () => {
      const app = await createApp(noActor());
      const res = await request(app).get(`/api/companies/${COMPANY_ID}/knowledge`);
      expect(res.status).toBe(401);
    });

    it("rejects cross-company access with 403", async () => {
      const otherCompany = randomUUID();
      const app = await createApp(boardUser(USER_ID, [COMPANY_ID]));
      const res = await request(app).get(`/api/companies/${otherCompany}/knowledge`);
      expect(res.status).toBe(403);
    });
  });

  describe("GET /api/knowledge/:pageId", () => {
    it("returns a page by ID", async () => {
      const app = await createApp(boardUser(USER_ID, [COMPANY_ID]));
      const res = await request(app).get(`/api/knowledge/${PAGE_ID}`);

      expect(res.status).toBe(200);
      expect(res.body).toMatchObject({ id: PAGE_ID, title: "Onboarding Guide" });
    });

    it("returns 404 for non-existent page", async () => {
      mockKnowledgeService.getById.mockResolvedValue(null);
      const app = await createApp(boardUser(USER_ID, [COMPANY_ID]));
      const res = await request(app).get(`/api/knowledge/${randomUUID()}`);
      expect(res.status).toBe(404);
    });
  });

  describe("GET /api/companies/:companyId/knowledge/slug/:slug", () => {
    it("returns a page by slug", async () => {
      const app = await createApp(boardUser(USER_ID, [COMPANY_ID]));
      const res = await request(app).get(`/api/companies/${COMPANY_ID}/knowledge/slug/onboarding-guide`);

      expect(res.status).toBe(200);
      expect(res.body).toMatchObject({ slug: "onboarding-guide" });
    });

    it("returns 404 for non-existent slug", async () => {
      mockKnowledgeService.getBySlug.mockResolvedValue(null);
      const app = await createApp(boardUser(USER_ID, [COMPANY_ID]));
      const res = await request(app).get(`/api/companies/${COMPANY_ID}/knowledge/slug/nonexistent`);
      expect(res.status).toBe(404);
    });
  });

  describe("POST /api/companies/:companyId/knowledge", () => {
    it("creates a new knowledge page", async () => {
      const app = await createApp(boardUser(USER_ID, [COMPANY_ID]));
      const res = await request(app)
        .post(`/api/companies/${COMPANY_ID}/knowledge`)
        .send({ title: "Onboarding Guide", body: "# Welcome" });

      expect(res.status).toBe(201);
      expect(res.body).toMatchObject({ title: "Onboarding Guide" });
      expect(mockLogActivity).toHaveBeenCalled();
    });

    it("rejects empty title with 400", async () => {
      const app = await createApp(boardUser(USER_ID, [COMPANY_ID]));
      const res = await request(app)
        .post(`/api/companies/${COMPANY_ID}/knowledge`)
        .send({ title: "", body: "content" });
      expect(res.status).toBe(400);
      expect(res.body.error).toContain("Title is required");
    });

    it("rejects title over 200 characters with 400", async () => {
      const app = await createApp(boardUser(USER_ID, [COMPANY_ID]));
      const res = await request(app)
        .post(`/api/companies/${COMPANY_ID}/knowledge`)
        .send({ title: "x".repeat(201), body: "content" });
      expect(res.status).toBe(400);
      expect(res.body.error).toContain("200 characters");
    });
  });

  describe("PATCH /api/knowledge/:pageId", () => {
    it("updates a knowledge page", async () => {
      const app = await createApp(boardUser(USER_ID, [COMPANY_ID]));
      const res = await request(app).patch(`/api/knowledge/${PAGE_ID}`).send({ title: "Updated Title" });

      expect(res.status).toBe(200);
      expect(mockKnowledgeService.update).toHaveBeenCalled();
    });

    it("rejects editing immutable HR documents with 403", async () => {
      mockKnowledgeService.getById.mockResolvedValue(MOCK_HR_PAGE);
      const app = await createApp(boardUser(USER_ID, [COMPANY_ID]));
      const res = await request(app).patch(`/api/knowledge/${MOCK_HR_PAGE.id}`).send({ title: "Hacked" });
      expect(res.status).toBe(403);
      expect(res.body.error).toContain("HR documents are immutable");
    });
  });

  describe("DELETE /api/knowledge/:pageId", () => {
    it("deletes a knowledge page", async () => {
      const app = await createApp(boardUser(USER_ID, [COMPANY_ID]));
      const res = await request(app).delete(`/api/knowledge/${PAGE_ID}`);

      expect(res.status).toBe(200);
      expect(res.body).toEqual({ ok: true });
      expect(mockKnowledgeService.remove).toHaveBeenCalledWith(PAGE_ID);
    });
  });

  describe("GET /api/knowledge/:pageId/revisions", () => {
    it("lists revisions for a page", async () => {
      const app = await createApp(boardUser(USER_ID, [COMPANY_ID]));
      const res = await request(app).get(`/api/knowledge/${PAGE_ID}/revisions`);

      expect(res.status).toBe(200);
      expect(res.body).toHaveLength(1);
    });

    it("returns 404 if page does not exist", async () => {
      mockKnowledgeService.getById.mockResolvedValue(null);
      const app = await createApp(boardUser(USER_ID, [COMPANY_ID]));
      const res = await request(app).get(`/api/knowledge/${randomUUID()}/revisions`);
      expect(res.status).toBe(404);
    });
  });

  describe("POST /api/knowledge/:pageId/revisions/:revisionNumber/revert", () => {
    it("reverts to a specific revision", async () => {
      const app = await createApp(boardUser(USER_ID, [COMPANY_ID]));
      const res = await request(app).post(`/api/knowledge/${PAGE_ID}/revisions/1/revert`);

      expect(res.status).toBe(200);
      expect(mockKnowledgeService.revertToRevision).toHaveBeenCalled();
      expect(mockLogActivity).toHaveBeenCalled();
    });
  });
});
